version: '3.9'

services: 
  api:
    build:
      dockerfile: Dockerfile.API
    ports:
      - "6000:80"
    image: postgres
  web:
    build:
      dockerfile: Dockerfile.WEB
    ports:
      - "5000:80"
    image: "bakery-web:${API_URL}"