version: '3.9'

services: 
  api:
    build:
      dockerfile: Dockerfile.API
    ports:
      - "6000:80"
  web:
    build:
      dockerfile: Dockerfile.WEB
    ports:
      - "5000:80"
    environment:
      - API_URL: http://localhost:6000