# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /

# copy csproj and restore as distinct layers
COPY bakery-web.sln .
COPY bakery-web/*.csproj ./bakery-web/
COPY bakery-data/*.csproj ./bakery-data/
RUN dotnet restore

# copy everything else and build app
COPY bakery-web/. ./bakery-web/
COPY bakery-data/. ./bakery-data/

WORKDIR /bakery-web
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "bakery-web.dll"]