version: '3.9'

services: 
  api:
    image: martinstokholm23/bakery-api:latest
    build:
      dockerfile: Dockerfile.API
    ports:
      - "6000:80"
  web:
    image: martinstokholm23/bakery-web:latest
    build:
      dockerfile: Dockerfile.WEB
    ports:
      - "5000:80"
    environment:
      - API_URL=http://api:80